### ISSUE TITLE
clarify the name

### ISSUE THREAD

**Issue by blshkv** [nabla-c0d3/tls_parser#2]
there are two names currently: with _ and with -. Please use one of them everywhere.

https://github.com/nabla-c0d3/sslyze/blob/master/requirements.txt:
```
tls-parser==1.0.0
```

https://pypi.python.org/pypi/tls-parser download:
```
https://pypi.python.org/packages/c9/30/.../tls_parser-1.0.0.zip
```

**Comment by nabla-c0d3** [comment]
Pip and Pypi automatically turn underscores into dashes, which is quite annoying: http://pybuilder.github.io/documentation/external_plugins.html

**Comment by nabla-c0d3** [comment]
...And doesn't make sense since Python package names can't contain dashes.
